### 获取用户信息
GET http://localhost:8888/eusr/getUserInfo
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVVUlEIjoiY2Y1YWU2YzItNTg1OC00MzdkLTg0NTUtZTU5MmQ3YTExNTQ0IiwiSUQiOjEsIlVzZXJuYW1lIjoiYWRtaW4iLCJOaWNrTmFtZSI6ImFkbWluIiwiQXV0aG9yaXR5SWQiOjg4OCwiQnVmZmVyVGltZSI6ODY0MDAsImlzcyI6InFtUGx1cyIsImF1ZCI6WyJHVkEiXSwiZXhwIjoxNzI3MDgxNTk3LCJuYmYiOjE3MjY0NzY3OTd9.wZVdOLAdl1RMG29dkb5Kp7FtVoizlM967ZmU3N428h4

